import "./globals.css";

export const metadata = {
  title: "Coffee shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-Dana bg-gray-100 dark:bg-zinc-800">{children}
      </body>
    </html>
  );
}
